# Generated by Django 2.2.1 on 2019-09-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacant_seats',
            name='id',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
