# Generated by Django 2.2.1 on 2019-09-06 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0002_auto_20190906_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacant_seats',
            name='seats_and_user',
        ),
        migrations.AlterField(
            model_name='vacant_seats',
            name='will_vacant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert.Profile', verbose_name='空席までの時間'),
        ),
    ]
