# Generated by Django 2.2.1 on 2019-09-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0003_auto_20190906_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacant_seats',
            name='id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
