# Generated by Django 2.2.1 on 2019-09-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0004_auto_20190906_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacant_seats',
            name='seats_and_user',
            field=models.ManyToManyField(to='expert.Profile'),
        ),
        migrations.AlterField(
            model_name='vacant_seats',
            name='id',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vacant_seats',
            name='will_vacant',
            field=models.IntegerField(verbose_name='空席までの時間'),
        ),
    ]
