# Generated by Django 2.2.1 on 2019-09-06 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0005_auto_20190906_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacant_seats',
            name='seats_and_user',
        ),
        migrations.AlterField(
            model_name='vacant_seats',
            name='id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vacant_seats',
            name='will_vacant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert.Profile', verbose_name='ユーザー情報'),
        ),
    ]
