# Generated by Django 2.2.1 on 2019-09-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0006_auto_20190906_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='駅ID')),
                ('name', models.CharField(max_length=50, verbose_name='駅名')),
            ],
            options={
                'verbose_name': '駅データ',
                'verbose_name_plural': '駅データ',
            },
        ),
    ]
