# Generated by Django 2.2.1 on 2019-09-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0007_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacant_seats',
            name='car_number',
            field=models.CharField(default='', max_length=2, verbose_name='号車'),
        ),
        migrations.AddField(
            model_name='vacant_seats',
            name='door_number',
            field=models.CharField(default='', help_text='進行方向に最も近い座席の場合は0です', max_length=1, verbose_name='進行方向からのドア数'),
        ),
        migrations.AddField(
            model_name='vacant_seats',
            name='seat_number',
            field=models.CharField(default='', max_length=1, verbose_name='進行方向からの席数'),
        ),
        migrations.AddField(
            model_name='vacant_seats',
            name='seat_place',
            field=models.IntegerField(choices=[(0, '右'), (1, '左')], default=0, verbose_name='進行方向に対する場所'),
        ),
    ]
