# Generated by Django 2.2.1 on 2019-09-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0008_auto_20190910_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacant_seats',
            name='seat_place',
            field=models.IntegerField(choices=[(0, '右'), (1, '左')], default=2, verbose_name='進行方向に対する場所'),
        ),
    ]
