# Generated by Django 2.2.1 on 2019-09-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0010_auto_20190911_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Give',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '',
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='give_point',
            field=models.IntegerField(default=10, verbose_name='ゆずりポイント'),
        ),
    ]
