# Generated by Django 2.2.1 on 2019-09-11 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0012_auto_20190911_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacant_seats',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='タイムスタンプ'),
            preserve_default=False,
        ),
    ]
