# Generated by Django 2.2.1 on 2019-09-11 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0013_vacant_seats_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacant_seats',
            name='will_vacant',
        ),
    ]
