# Generated by Django 2.2.1 on 2019-09-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0014_remove_vacant_seats_will_vacant'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacant_seats',
            name='is_vacant',
            field=models.BooleanField(default=True),
        ),
    ]
