# Generated by Django 2.2.1 on 2019-09-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0015_vacant_seats_is_vacant'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacant_seats',
            name='board_station',
            field=models.CharField(default='', max_length=70, verbose_name='乗車駅'),
        ),
        migrations.AddField(
            model_name='vacant_seats',
            name='exit_station',
            field=models.CharField(default='', max_length=70, verbose_name='降車駅'),
        ),
    ]
