# Generated by Django 2.2.1 on 2019-09-12 04:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0016_auto_20190912_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacant_seats',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='タイムスタンプ'),
        ),
    ]
