# Generated by Django 2.2.1 on 2019-09-12 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0018_auto_20190912_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(default='', max_length=2, verbose_name='号車')),
                ('board_station', models.CharField(default='', max_length=70, verbose_name='乗車駅')),
                ('exit_station', models.CharField(default='', max_length=70, verbose_name='降車駅')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert.Profile', verbose_name='ユーザー情報')),
            ],
            options={
                'verbose_name': '起立ユーザーデータ',
                'verbose_name_plural': '起立ユーザーデータ',
            },
        ),
    ]
