# Generated by Django 2.2.1 on 2019-09-12 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0019_waituser'),
    ]

    operations = [
        migrations.AddField(
            model_name='waituser',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='タイムスタンプ'),
        ),
    ]
