# Generated by Django 2.2.1 on 2019-09-12 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0020_waituser_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waituser',
            name='profile',
        ),
    ]
